# Generated by Django 4.0 on 2021-12-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='data_add',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
