# Generated by Django 4.0 on 2021-12-27 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('blogs', '0002_alter_blogpost_data_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
