# Generated by Django 4.0 on 2021-12-27 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blogpost_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='usuario',
            new_name='proprietario',
        ),
    ]
