# Generated by Django 4.0 on 2021-12-28 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_blogpost_capa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='capa',
        ),
    ]
